A_APP_NAME = despot3900.win64.exe

A_BIN_MEDIA = true

#
# You can set A2X_PATH to a hard-coded value
# if you do not have a2x/bin in your $PATH
#
A2X_PATH := $(shell a2x_path)
include $(A2X_PATH)/make/project/Makefile.mingw64
