APP = 38th-century
BIN_DIR = ../bin
SRC_DIR = ../src
GFX_DIR = ../gfx
SFX_DIR =
OBJ_DIR = ../obj

#
# You can set A2X_PATH to a hard-coded value
# if you do not have a2x/bin in your $PATH
#
A2X_PATH := $(shell a2x_path)
include $(A2X_PATH)/make/project/Makefile.linux
